### ISSUE TITLE
Windows Admin Rights

### ISSUE THREAD

**Issue by JAK1047** [ossec/ossec-hids#1221]
I've installed this for a few different users in our environment. Problem being not all of them have local admin rights on their Windows machine. I've tried setting the ACLs on the program folder to give them full access on all objects and containers, but a few files either don't take the change (the version file and conf files remain as Administrators only whensetting perms with either icacls or Set-ACL) or don't seem to inherit (even though they have Full Control NTFS perms to tmp they receive an ACCESS DENIED when the agent tries to generate temporary files in it. Mainly when they try to save changes to the conf file).

Is there a means to give non-admins sufficient privileges, or should I just create a local admin account they can use to run it?

**Comment by ddpbsd** [comment]
It should run automatically, as I believe it's installed as a service.

**Comment by nbuuck** [comment]
It's difficult or even impossible to troubleshoot file system permissions without having a full listing of the file system objects and their DACLs - if you made a mistake, we wouldn't know given the information provided. That said, I can offer that it is [possible](https://technet.microsoft.com/en-us/library/cc731500%28v=ws.10%29.aspx) for any file system object to be excluded from inheriting ACEs (Access Control Entries) from parent objects, so you may need to manually add the desired ACEs to the objects you mentioned that aren't receiving the entries you've added to the parent directory.

There are some things to consider about allowing a non-admin to modify or control the agent:
- How often does a non-admin have cause to modify the agent? Changes to agents should be relatively infrequent, I imagine.
- Should you really be trusting a non-admin to control the agent in any way? The user could stop the agent at-will to obscure malicious activity or otherwise interrupt log collection, file integrity monitoring, and root-checking.
- ossec-agent.exe runs as `SYSTEM`. A user with permission to modify the installation directory could substitute a new binary in place of the agent image and achieve admin-levels permissions on the host.
