### ISSUE TITLE
Not all alerts in email

### ISSUE THREAD

**Issue by ekillian** [ossec/ossec-hids#1266]
This maybe a configuration issue on my part or a bug. I tried posting on the ossec-list but got response. I'm going to copy and paste what I wrote over there.

I'm running on CentOS 7.3.1611 and using the atomic repo which has ossec-hids-2.9.2-2082 and ossec-hids-server-2.9.2-2082.
I have done debugging and I'm seeing some things I think are strange.
If the condition I'm testing for has happened in the last 15 to 20 minutes before the
email is sent, the subject contains the alert message and the body contains the
alert message along with other alerts. If the condition is more than 25 to 30 minutes 
before the email is sent, the subject will still show the alert, but the alert message will
not be in the body of the email. Here are some stats from the emails today:

Email            Number         Earliest reported
Arrived          of alerts         alert
01:00             109               00:36
02:00             110                01:37
03:00             111                02:34
04:00             112                03:39
05:00             113                04:34
06:00             114                05:39
07:00             115                06:36
08:00             116                07:51
09:00             117                08:55
10:00             118                09:56

It seems strange that the number of alerts is incrementing by one each hour.
I went back further in the emails and it seems to increment to 186 and then
start over at 97.

**Comment by nbuuck** [comment]
@ekillian When you say "condition that I'm testing for", does "condition" mean the unknown circumstances that cause the anomaly between the email subject and body, or does "condition" mean a particular rule that you're alerting on?

1. Does this issue occur with a specific rule/decoder?
2. Have you used previous versions of ossec-hids-server with this configuration? If so, was this issue present in any previous version?
3. Can you provide examples of the two email results - normal subject and body versus subject only? The length and/or content of the SMTP subject and body could provide clues about the root cause.
4. Do the alerts corresponding to the anomalous emails appear intact in `/logs/alerts/alerts.log`?
5. What is your email configuration and mail flow (OSSEC -> some relay -> mail server, please describe)?

I'm fishing a bit here because, while you've been thorough in documenting a table of times, alert IDs, ... and another timestamp (in fact, I'm not quite sure what that table is trying to communicate with the second time field), the rest of your issue is some vague/abstract, such that it would be difficult for anyone to provide meaningful assistance at this point without more detail.

**Comment by ekillian** [comment]
Let me start by saying that we have decided to forego the email system within ossec-hids and write our own script to parse the /var/log/alerts/alerts.log file and email results. This will not only solve this issue, it will also allow us to customize the email for our needs. We will be able to do things like sort by alert level and put the highest alerts at the top of the email.
But I feel I still owe you answers to your questions.
When I say "condition that I'm testing for", that is a new rule I have written in local_rules.xml which is testing for a "condition" or event in the log files. 

1. I was going to say yes, it happens with a new rule that I wrote. But now that I think about it, it wouldn't matter because as far as I can see, only a certain number of alerts are included in the email. I only noticed it since I wrote a new rule which was producing an alert, but the alert wasn't included in the email. This may be a feature and not a bug.
2. No, I have only been working with this one version of ossec-hids-server.
3. Sorry, my management will not allow me to provide that information.
4. I think the problem is that we have the settings configured to only send one email per hour and there are too many alerts to include in the email.  An example would be that this morning between 8 AM and 9 AM there were 403 alerts in the alerts.log file but only 361 included in the email from ossec-hids.
5. OSSEC running on CentOS 7 -> Linux relay -> Exchange server.

In looking back at the way the message got reformatted, I can see that the columns are confusing. There are three columns. First column is when the email was sent. Second column is the number of alerts included in the email. Third column is the earliest alert that was in the email. So for the first row, The email was sent at 01:00 AM, with 109 alerts included, and the earliest alert was at 00:36 or 12:36 AM. The second row shows the email sent at 02:00 AM had 110 alerts included and the earliest alert was at 01:37 AM. In all cases there were more alerts for the one hour time frame than were included in the email. For the first row, there were alerts between 00:00 and 00:36 but they were not included in the email. For the second row, there were alerts between 01:00 and 01:37 that weren't included.

**Comment by nbuuck** [comment]
I greatly appreciate your thorough response, even though you don't intend to pursue this particular issue further with the ossec-hids project. Because this is a new rule and example data is - though understandably - not available, I don't believe this is something that the project could pursue resolution on its own. As such, I'm marking this issue as closed. You're welcome to re-open it if you have further thoughts or change your mind later.

**Comment by ddpbsd** [comment]
I'd love for maild to be replaced with something better. Maybe something in python. But that's long term thoughts.

**Comment by ekillian** [comment]
That's what I'm planning on writing my script in, Python.
