### ISSUE TITLE
ossec Agent with proxy server to ossec server

### ISSUE THREAD

**Issue by jllgando** [ossec/ossec-hids#1384]
i want to set my ossec agents (windows / linux) to go thru proxy server to communicate with ossec server it this possible?

**Comment by ddpbsd** [comment]
I'm not aware of any OSSEC proxies. I think there would be a number of issues with the idea.
Why do you feel like you need a proxy?

**Comment by mjejee** [comment]
Hi,

I would also be interested in this feature. In my case, the purpose of such proxies would be to aggregate agent connections to the manager. 

A potential use case would be a multi site architecture. There would be a proxy server on each location, which agents would connect to. Then, each proxy would establish a connection to the manager, aggregating all the data from the agents at their site. Thus, instead of having a great number of connections across different locations, there would be only one site-to-site connection per site.

Thank you :)

**Comment by ddpbsd** [comment]
@mjejee Couldn't that be accomplished with hybrid mode servers?

**Comment by mjejee** [comment]
Thank you for you fast response :)

No, I don't think so. From what I understood, that would reduce the traffic sent to the server, as logs would be analysed locally. However, that's not what I am trying to accomplish, I probably didn't explain it right. My intention is to get all the log data in the central server, but aggregating the connections on a per site basis. 

Best regards.

**Comment by atomicturtle** [comment]
Thats definitely something I use hybrid configs for now
