### ISSUE TITLE
What exactly ossec features ? Was it HIDS or HIPS or both ?

### ISSUE THREAD

**Issue by gagantous** [ossec/ossec-hids#1442]
i read on ossec documentation, said:

> OSSEC is a scalable, multi-platform, **open source Host-based Intrusion Detection System (HIDS)**. It has a powerful correlation and analysis engine, integrating log analysis, file integrity checking, Windows registry monitoring, centralized policy enforcement, rootkit detection, real-time alerting and active response.It runs on most operating systems, including Linux, OpenBSD, FreeBSD, MacOS, Solaris and Windows.

How could, ossec is HIDS, while it has "active-response" which could be categorized as HIPS features. Or is it both ?

**Comment by gagantous** [comment]
@ddpbsd 

It does matter because i have to explain to my lecturer about this application, it's in my thesis

**Comment by atomicturtle** [comment]
Its a little semantic of a question.  OSSEC does respond to attacks with actions, depending on where those attacks are detected (and how) that could occur before or after an event is successful: For example, ossec is very effective at detecting a brute force attack. Multiple login failures from a source across one or more services. This would be an example of an IPS. 

However it is not good at detecting web based attacks (SQLi), since the request is made & successful, then logged, then analyzed and finally responded to.  In that context the attack  would be successful the first time, then triggering an action like a firewall drop. 

But I guess you could just look at the name of the project too... dcid called it the Open Source Host-based Intrusion Detection System. So there you go... its in the name right there.
