### ISSUE TITLE
Debian Buster Packages

### ISSUE THREAD

**Issue by ssgelm** [ossec/ossec-hids#1742]
Hi,

I noticed that there are no packages for buster.  Also, the script used to create the package at https://github.com/ossec/ossec-hids/tree/master/contrib/debian-packages seems outdated.  Will you be providing buster debs soon?  Can the current packaging be open sourced?

**Comment by sscotter** [comment]
I too am interested in sourcing packages compatible with Debian 10 aka Buster.

**Comment by atomicturtle** [comment]
sure, we could use your help on that. The best place to coordinate this is on slack, you can email us for an invite: slack@ossec.net

**Comment by kinimoas** [comment]
I'm also interested in a new version von Debian 10.

Any progress on this?

**Comment by AllenRDCo** [comment]
I see packages for Buster now: https://updates.atomicorp.com/channels/atomic/debian/dists/buster/main/binary-amd64/Packages

Unfortunately they are listing both libssl1.1 and libssl1.0.0 as dependencies. libssl1.0.0 was dropped in buster so the packages are currently un-installable.

**Comment by brechsteiner** [comment]
any updates here?

**Comment by AllenRDCo** [comment]
> any updates here?

None I have seen. I ended up tearing apart the packages and fixing the debian/control file after verifying with ldd the binaries were only built with libssl 1.1 and then repackaged them and put them in my custom backports repo. I emailed the guy listed as the maintainer but have received no reply. 

Their support team simply told me they don't provide support for the open source repo's anymore, which I am not sure when that happened since there's no announcement about it that I can find, and it was only a few months ago they added the Buster packages.

**Comment by sscotter** [comment]
@AllenRDCo, are you able to share the exact process you performed to remove the dependency on libssl 1.1?

Thanks!

**Comment by AllenRDCo** [comment]
```
mkdir {original,fixed,agent,server}
cd original
wget https://updates.atomicorp.com/channels/atomic/debian/pool/main/o/ossec-hids-agent/ossec-hids-agent_3.3.0.8264buster_amd64.deb
wget https://updates.atomicorp.com/channels/atomic/debian/pool/main/o/ossec-hids-server/ossec-hids-server_3.3.0.8264buster_amd64.deb

cd ../

dpkg-deb -R original/ossec-hids-agent_3.3.0.8264buster_amd64.deb agent
# edit DEBIAN/control to remove the extraneous dependency for libssl 1.0.0
dpkg-deb -b agent fixed/ossec-hids-agent_3.3.0.8264buster_amd64.deb

dpkg-deb -R original/ossec-hids-server_3.3.0.8264buster_amd64.deb server
# edit DEBIAN/control to remove the extraneous dependency for libssl 1.0.0
dpkg-deb -b server fixed/ossec-hids-server_3.3.0.8264buster_amd64.deb
```

Then you can either install directly using `dpkg -i <deb file>` or add them to your own custom repo if you have one. By not changing the package names if they ever fix their packages then they will cleanly upgrade from their repo.

**Comment by atomicturtle** [comment]
Actually since you guys dont seem to be afraid to get your hands dirty, can you check if the 3.4.0 testing packages manifest this issue still?

https://updates.atomicorp.com/channels/atomic-testing/debian/

**Comment by AllenRDCo** [comment]
Looks fine to me:
```~/testing/ossec $ wget https://updates.atomicorp.com/channels/atomic-testing/debian/ossec-hids-server_3.4.0.9229buster_amd64.deb
--2019-10-15 15:29:44--  https://updates.atomicorp.com/channels/atomic-testing/debian/ossec-hids-server_3.4.0.9229buster_amd64.deb
Resolving updates.atomicorp.com (updates.atomicorp.com)... 46.105.102.32, 192.99.9.170, 46.105.121.84, ...
Connecting to updates.atomicorp.com (updates.atomicorp.com)|46.105.102.32|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 716532 (700K) [application/x-troff-man]
Saving to: ‘ossec-hids-server_3.4.0.9229buster_amd64.deb’

ossec-hids-server_3.4.0.9229buster_amd64.deb                100%[========================================================================================================================================>] 699.74K  1.05MB/s    in 0.6s    

2019-10-15 15:29:46 (1.05 MB/s) - ‘ossec-hids-server_3.4.0.9229buster_amd64.deb’ saved [716532/716532]

~/testing/ossec $ mkdir agent
~/testing/ossec $ dpkg-deb -R ossec-hids-server_3.4.0.9229buster_amd64.deb agent
~/testing/ossec $ grep Depends agent/DEBIAN/control 
Depends: libc6 (>= 2.27), libevent-2.1-6 (>= 2.1.8-stable), libgeoip1, libmariadb3 (>= 3.0.0), libpcre2-8-0 (>= 10.32), libssl1.1 (>= 1.1.0), zlib1g (>= 1:1.2.3.3), expect, debconf
```

**Comment by AllenRDCo** [comment]
My guess is that the packaging process for the stable Buster packages had the libssl 1.0.0 depends set as a manually added entry to the Depends in the control, rather than relying on the automatic depends generation usually available in the packaging tools. I have no idea what y'all are using, but when I package up stuff I use pbuilder, and rarely do I need to manually adjust the Depends line.

**Comment by atomicturtle** [comment]
Its a glorious cathedral! :P  We build more than 30 distributions concurrently (AIX, Solaris, Debian, Ubuntu, Centos, Redhat, Amazon, Windows, etc) so there is a fair amount of conditional building. The process is semi-sorta-kinda built around mock (dar really... if you're that old) and the rpm spec file. Everything else (Solaris aside...)  forks out from that. We did used to use pbuilder at one point, but due to maintenance overhead that didnt work in this kind of CI chain

**Comment by atomicturtle** [comment]
PS- let me know if you want a slack invite, I could always use the input from another packager!

**Comment by AllenRDCo** [comment]
No worries. I get that it's a big project to handle packaging for several OS's, let alone just one. I don't like doing it myself, and that's just for a handful of packages in-house. It was just frustrating getting a poor response from your support group about something that was so trivial to fix, especially when the response was "We don't do that anymore, here, pay for our Enterprise solution instead!" even though clearly you still do maintain the public repos.

Buster has been especially irritating, for some reason this time around several major 3rd parties struggled to get packages out for it in time in the first place, and a couple of them either pulled the packages (Saltstack, their 2019.2.1 release was too buggy so they pulled everything back for that so now there are no packages for Buster until the end of the month when 2019.2.2 is released) or are using an improper signing key for the repo so apt won't accept the key anymore (Duo). I'm just barely starting to get Buster on production systems and that's still without full support from the 3rd party packages we need.

I'm no expert packager by any stretch of the imagination. I just mangle, er, manage several packages for in-house use due to either custom in-house software, custom build needs for existing packages, or it's taking too long for someone to fix their code (not just you, there are others and I am dragging my feet backporting their packages with the fixes we need because I am lazy). I'll email you though from my work address to get a Slack invite.

**Comment by sscotter** [comment]
@AllenRDCo thanks dude, much appreciated!

**Comment by sda399** [comment]
hi!
we've got stretch packages in buster repo:

```
# cat /etc/apt/sources.list.d/ossec.list 
deb https://updates.atomicorp.com/channels/atomic/debian buster main
#
#apt search ossec
Sorting... Done
Full Text Search... Done
ossec-hids-agent/unknown 3.4.0.9229stretch amd64
...
```

**Comment by atomicturtle** [comment]
Thanks again for the report!
