### ISSUE TITLE
Systems without libevent 1 won't compile

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-hids#1860]
@upengan78  encountered the following problem in #1785 

```
5- Installing the system

    Running the Makefile
    cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR="/var/ossec" -DUSER="ossec" -DREMUSER="ossecr" -DGROUPGLOBAL="ossec" -DMAILUSER="ossecm" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DLOCAL -Wall -Wextra -I./ -I./headers/ os_maild/sendmail.o os_maild/sendcustomemail.o os_maild/config.o os_maild/os_maild_client.o os_maild/maild.o os_maild/mail_list.o os_dns/os_dns.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a -lm -lpthread -lpcre2-8 -lssl -lcrypto -lz -levent ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-maild
    /bin/ld: cannot find -levent
    collect2: error: ld returned 1 exit status
    make: *** [ossec-maild] Error 1

Error 0x5.
Building error. Unable to finish the installation.
```

Changing `-levent` to `-lev` with the following packages installed allowed it to work:
```
libevent-2.0.21-4.el7.x86_64
libev-libevent-devel-4.15-3.el7.x86_64
```

The installer needs to figure out which library to use. There might be backwards compatibility in libevent2, can't remember.

**Comment by owlmind** [comment]
It looks like i have similar issue on Solaris 11.4.
Compiling breaks because of libevent.

ossec-hids-master/src]# C_INCLUDE_PATH="/usr/include/pcre" PCRE2_SYSTEM=yes gmake PREFIX=/opt/ossec TARGET=agent build
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/opt/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DSunOS -DSOLARIS -DHIGHFIRST -D_GNU_SOURCE -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -DCLIENT -Wall -Wextra -I./ -I./headers/  client-agent/notify.o client-agent/start_agent.o client-agent/receiver-win.o client-agent/main.o client-agent/receiver.o client-agent/event-forward.o client-agent/agentd.o client-agent/intcheck_op.o client-agent/config.o client-agent/sendmsg.o os_dns/os_dns.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a os_zlib.a  -lm -lsocket -lnsl -lresolv -lpcre2-8 -lssl -lcrypto -lz  -lev ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-agentd
./external/compat/imsg-buffer.c: In function ‘ibuf_write’:
./external/compat/imsg-buffer.c:153:20: error: ‘IOV_MAX’ undeclared (first use in this function)
  153 |  struct iovec  iov[IOV_MAX];
      |                    ^~~~~~~
./external/compat/imsg-buffer.c:153:20: note: each undeclared identifier is reported only once for each function it appears in
./external/compat/imsg-buffer.c:153:16: warning: unused variable ‘iov’ [-Wunused-variable]
  153 |  struct iovec  iov[IOV_MAX];
      |                ^~~
./external/compat/imsg-buffer.c: In function ‘msgbuf_write’:
./external/compat/imsg-buffer.c:231:20: error: ‘IOV_MAX’ undeclared (first use in this function)
  231 |  struct iovec  iov[IOV_MAX];
      |                    ^~~~~~~
./external/compat/imsg-buffer.c:231:16: warning: unused variable ‘iov’ [-Wunused-variable]
  231 |  struct iovec  iov[IOV_MAX];
      |                ^~~
gmake: *** [Makefile:1022: ossec-agentd] Error 1

However workaround with replacing -levent to -lev doesn't help.

I can compile 3.3, but all 3.4 and higher versions wouldn't compile with this error.

**Comment by ddpbsd** [comment]
@owlmind That's not because of the libevent, it's from the imsg stuff. Looks like IOV_MAX isn't defined on Solaris (at least not in the headers we include. This might help: https://github.com/ddpbsd/ossec-hids/commit/3c029c37a17a1c0c227112bde9158898b22a1337
If you have a chance to test it, and it works, I'll open a pull request for it.

**Comment by owlmind** [comment]
> 
> 
> @owlmind That's not because of the libevent, it's from the imsg stuff. Looks like IOV_MAX isn't defined on Solaris (at least not in the headers we include. This might help: [ddpbsd@3c029c3](https://github.com/ddpbsd/ossec-hids/commit/3c029c37a17a1c0c227112bde9158898b22a1337)
> If you have a chance to test it, and it works, I'll open a pull request for it.

This helped. Compiled succesfully.
Thank you.

**Comment by atomicturtle** [comment]
Closed as resolved
