### ISSUE TITLE
Agent key generated differently between manage_agents and ossec-authd

### ISSUE THREAD

**Issue by torrancew** [ossec/ossec-hids#190]
It would appear that the code used to generate agent keys in [manage_agents](https://github.com/ossec/ossec-hids/blob/master/src/addagent/manage_agents.c#L274-L304) is entirely different from the analogous code in [ossec-authd](https://github.com/ossec/ossec-hids/blob/master/src/addagent/validate.c#L43-L80) - mainly:
- In [ossec-authd](https://github.com/ossec/ossec-hids/blob/master/src/addagent/validate.c#L46), `str1` has uname information added at the end, presumably as extra entropy - [comparison](https://github.com/ossec/ossec-hids/blob/master/src/addagent/manage_agents.c#L294).
- In [manage_agents](https://github.com/ossec/ossec-hids/blob/master/src/addagent/manage_agents.c#L295), `str2` contains an additional time delta at the beginning, presumably as extra entropy - [comparison](https://github.com/ossec/ossec-hids/blob/master/src/addagent/validate.c#L47).
- In [manage_agents](https://github.com/ossec/ossec-hids/blob/master/src/addagent/manage_agents.c#L300-L302), `str1` is reset to a new string, based on its original MD5, the PID, the time, and yet another random number, and them re-MD5'd - again, presumably for extra entropy. There is no point of comparison here as this function is simply not performed at all in `ossec-authd`.

The third seems a bit hand-wavey to me, but perhaps I'm simply being a bit dense there.

The end result seems to be a key that is the concatenation of 2 MD5 sums - perhaps a single SHA256 would be simpler?

**Comment by plastikman** [comment]
In the spirit of manage_agents and ossec-authd being different...here is something I have noticed that is currently causing a problem with my install (Using AlienVault).

manage_agents requires a hostname and an IP.  ossec-authd/agent-auth do not require an IP address.

Here is the way I add my hosts with manage_agents

Create a flat file that is <hostname>,<IP Addr>
Import the file using "/var/ossec/bin/manage_agents -f <file>

the output of list agents looks like this:
`ID: 001, Name: hostname.example.com, IP: x.x.x.x`

When I add hosts with the agent-auth no IP address is required.  With AlienVault this is  problem because assets do not map with agents (I have already opened an issue with AlienVault).

with an agent added using agent-auth the output looks like this:

`ID: 1024, Name: hostname.example.com, IP: any`

Is it possible to force agent-auth to provide an IP address (perhaps the primary interface) or allow me to specify one when adding the host?
