### ISSUE TITLE
Building Windows Agent from Sources

### ISSUE THREAD

**Issue by ccx004** [ossec/ossec-hids#418]
There seems to be an error in the ossec-installer.nsi file. On line 149 there is a line which specifies the name of the conf file that should be used as the default configuration file for ossec. However, the file specified doesn't exist in the distribution nor is it constructed. There is a file called default-ossec.conf which seems to be the correct one.

**Comment by jrossi** [comment]
Build on windows is not support we welcome people to back port all changes from makefiles and make.sh to make.bat but at this time it's not something we have the man power to support.  

We are doing this because we don't have an automated way to build not windows using Travis ci or something else that does the same thing.  But requests will be accepted :)
