### ISSUE TITLE
Packaging OSCEC

### ISSUE THREAD

**Issue by szepeviktor** [ossec/ossec-hids#517]
Do you plan to package OSSEC for Debian and RPM?

For now: Is there an upgrade/uninstall documentation?

OSSEC feels promising for me.

**Comment by atomicturtle** [comment]
Yeah, up on the web site: http://www.ossec.net/?page_id=19

**Comment by szepeviktor** [comment]
Oh! Thank you!

**Comment by szepeviktor** [comment]
I see you have an `all-in-/var` approach.
Does it serve a specific purpose?
I've never seen a Debian package that looks like this.

**Comment by szepeviktor** [comment]
I know it takes a lot of effort to debianize a software pkg.

**Comment by santiago-bassett** [comment]
Hi viktor,

Ossec runs in his own little chroot environment in /var/ossec/

No matter if you use the deb or rpm installers, or even if you install it from sources it will always go to that folder by default.

I dont think it is recommended to change its location since there might be some hardcoded paths. In any case, if it is a must, i would have a look to the code and installation scripts

Santiago Bassett
@santiagobassett

**Comment by szepeviktor** [comment]
Thank you!
