### ISSUE TITLE
Active response stop working

### ISSUE THREAD

**Issue by tvidal-34** [ossec/ossec-hids#518]
Dear Ossec team,

I did all http://ossec-docs.readthedocs.org/en/latest/faq/unexpected.html
And I'm working more than 1 week on this issue (https://groups.google.com/forum/#!topic/ossec-list/Qs0C0JmjVFM).
The last thing that I can do is to recompile with more verbose output.
But can I ask you a little bit help for that ?
I would like to get verbose output when server get an alert that should send firewall-drop active response to agents. Can you let me know what file and function I need to change ?
Many thanks and all the best

Thomas

**Comment by jrossi** [comment]
Please understand that we know you are having an issue, but not enough users are reporting a problem for us to think this is more then a configuration or a host issue with the installation.  Active Response has a history of being hard to get working as people expect and not a simple "enable" and works feature.    At this time I don't think this is a bug without more details with the code.   I would suggest using the mailing most to seek answers from a wider audience.  While i understand that you have done so, please include alot more details of what is going on so that people can help.  I would suggest post the configuration in palce and detail logs to gist.github.com so people can see the details for them selves.
