### ISSUE TITLE
C compiler is a risk

### ISSUE THREAD

**Issue by yeshuat** [ossec/ossec-hids#760]
Hi,

I am wondering if you can help?

We have implemented the OSSEC Agents on our linux machines and having the C compiler installed on our machines is a risk.  Is there a way around this?  We have been told that we can just remove the C compiler after installing the agents but this is extremely inconvenient.

If there is no way around this, can this please be raised a

**Comment by netman2k** [comment]
What os do you use in your environment? If you are using redhat derives you
can install rpm installation insted of compile one

**Comment by yeshuat** [comment]
RedHat we are using.  We took this approach... These were the steps we took:

1. Removed the make commands out of the install.sh
2. Ran the make command in a separate script on a local VM
3. Packaged this back up and created an RPM out of this
4. We then tested the RPM but the set-up was different.

On the menu, importing the key wasnt an option.  When deploying the RPM on a host, it didnt seem to recognise the host as an agent - it asked to add an agent despite me deploying it on that host

Was this the approach you were thinking of?

**Comment by aquerubin** [comment]
On Mon, 7 Mar 2016, yeshuat wrote:

> We have implemented the OSSEC Agents on our linux machines and having 
> the C compiler installed on our machines is a risk.  Is there a way 
> around this?  We have been told that we can just remove the C compiler 
> after installing the agents but this is extremely inconvenient.
>
> If there is no way around this, can this please be raised a

1.  Build/install the agent on one development machine that does have a 
compiler.

2.  In your build directory, copy etc/preloaded-vars.conf.example to 
etc/preloaded-vars.conf.  Modify preloaded-vars.conf and un-comment 
'#USER_BINARY'

3.  Tar up the whole directory and copy the tarball to each agent.

4.  On each agent run the installer.


Antonio Querubin
e-mail:  tony@lavanauts.org
xmpp:  antonioquerubin@gmail.com

**Comment by dcid** [comment]
I need to add in here:

- Having a C compiler is not a risk. If anyone ever told you that, please disregard their opinion :)

I bet your system already has Perl, bash, Python and other programming languages installed in there, so being able to compile something in C is not something to be concerned about. If you are worried about an attacker being able to compile something, I assure you that not having a compiler won't stop him. In fact, most exploits and backdoors I see in the wild use non-compiled languages, like Perl and PHP.

Unrelated to the topic of mass deploying agents, but not having a C compiler because of a risk should not deter you.

thanks,

**Comment by ddpbsd** [comment]
This issue is covered in the documentation, and seems to be answered very well here.
