### ISSUE TITLE
False ossec-agent connectivity status on ossec 2.8.3

### ISSUE THREAD

**Issue by ppatel-cc** [ossec/ossec-hids#861]
Team,
I have faced multiple issues where I can see ossec agent_control script giving false output of connectivity status. I can receive real time logs whereas the agent_control script gives me Never connected or disconnected.

Can you please review the script and/or provide us if patched already.

Thanks!
Pranav Patel

**Comment by ddpbsd** [comment]
Check the files in `/var/ossec/queue/agent-info` to make sure they're up to date. If not, check the permissions on the files. You could try clearing the ones that are incorrect, or maybe deleting them. I haven't tried this, so I'm not sure if it'll have an impact on anything.

**Comment by heaviss** [comment]
Hi @ddpbsd ! I have a same problem.
What permissions should be on files? 
Before update to version 2.8.3 it was "-rwxr-----", now "-rw-r--r--". Owner is "ossecr : ossec". Does the X flag matter?
And what's the frequency of checking the availability of agents? I noticed that the firewall drops packets from the server to the agent due to the fact that the session timeout (20 minutes) has been exceeded. I tried to increase the udp:1514 timeout to 1 hour, it didn't help.

**Comment by ddpbsd** [comment]
I have
```
# ls -l
-rw-r--r--  1 ossecr  ossec  108 Aug 12 09:03 junction-192.168.x.x
```

I don't know what the timeouts are off hand.

**Comment by acid-reign** [comment]
I believe I am having the same issue with a clean install of v2.9.3, I have setup one server and one agent. The server shows the agent has "Never connected" in agent_control, and server logs shows no mention of the agent.

However the agent's logs show it has connected to the server-ip: 
> ossec-agentd: INFO: Connected to server <server-ip>, port 1514.

and periodically shows: 
> ossec-agentd: DEBUG: Sending agent notification

The server has nothing in "/var/ossec/queue/agent-info/", and there aren't any other relevant error messages.
 (a few from logcollector about certain log files unavailable, because default <localfile> settings haven't been removed)

Firewall is not an issue, I was able to do `nc -u -l <server-ip> 1514` (listen on server) and `nc -u <server-ip> 1514` (connect from agent) and pass text back and forth

**Comment by ddpbsd** [comment]
Check the permissions on `/var/ossec/queue/agent-info`. Your agents are obviously connected, but the file with their info isn't getting written.

**Comment by acid-reign** [comment]
Since my comment, I noticed that the connected status doesn't change until after syscheckd finished the startup scan, and this was taking up to an hour for each agent. Disabling the startup scan made the agents show up as "connected" much faster.
