### ISSUE TITLE
OSSEC Agent high CPU usage with CentOS 6.8

### ISSUE THREAD

**Issue by stannikolayenko** [ossec/ossec-hids#957]
Hi, did anyone else experiencing OSSEC 2.8.3 agent high CPU usage with CentOS 6.8 systems?  We are spiking at 80 to 100%.  Is there a way to tune down how much CPU should be used for the scanning?

Thanks

**Comment by atomicturtle** [comment]
Which daemon?

**Comment by stannikolayenko** [comment]
Thank you for reply: "ossec-syscheck"

**Comment by stannikolayenko** [comment]
Thank you for your reply: “ossec-syscheck”

Stan Nikolayenko
stann@stanford.edu
(650)736-7527

**Comment by atomicturtle** [comment]
so syscheck handles both the FIM and the rootcheck events. This is entirely a disk I/O related, the CPU element of this is just the file hash and/or diff calculation based off the number of files you are monitoring from this.  That means that if you are doing both FIM (<syscheck>) and Rootkit checks (<rootcheck>) syscheck is going to run twice. There is no one solution here, but here are some ideas you can try out:

1) Use real-time FIM and increase the <frequency> section (I use 24 hours). Con: Increasing the frequency means a longer period to detect new files. Also this consumes inotify watches, make sure you increase that
2) Use Cgoups disk I/O limits, Cons: Scans take longer, detecting new files takes longer
3) Increase syscheck.sleep in internal_options.conf Con: Scans take a LOT longer, same w/ new file detection. 
4) Reduce the number of directories you're watching. Con: Reduces your auditing 
5) Use the <regex> type to limit watching to specific files. Con: Reduces your auditing 
6) Disable report_changes on some or all directories. Con: Really reduces your auditing 
7) Use the <ignore> tag on files and/or directories that change frequently. This is especially useful if you're using report_changes because it also saves disk space.  Con: Reduces your auditing

**Comment by stannikolayenko** [comment]
Thank you for the reply! this is excellent
