### ISSUE TITLE
Instruction to build deb package

### ISSUE THREAD

**Issue by efficks** [ossec/ossec-hids#999]
I've read the readme in ossec-hids/contrib/debian-packages and I'm not able to correctly build the debian package.
Also, the script seems to only build the package for version 2.8.2 instead of version 2.8.3.
Do you have any instruction to build the debian package somewhere? Can it be copied somewhere?

Thank you

**Comment by dmitrijn** [comment]
you can download debian/ubuntu already built packages from wazuh repo, you can find it here - http://documentation.wazuh.com/en/latest/ossec_installation_deb.html

**Comment by efficks** [comment]
@dmitrijn The problem is that I need to rebuild ossec to increate the number of agent via MAX_AGENTS variable.
What it the process to rebuild the deb after that?
Also, why the deb is on the wazuh server? Is it the same ossec or a fork?

**Comment by santiago-bassett** [comment]
Hi @dmitrijn 

packages ossec-hids (for the server component) and ossec-hids-agent (for the agent) are just OSSEC latest stable version (at this moment 2.8.3).  I packaged those and nothing else is in those packages.

I also contributed the Debian files and a simple script to automate the building at:
https://github.com/ossec/ossec-hids/blob/master/contrib/debian-packages/generate_ossec.sh

What problem are you running into? I may be able to help.

**Comment by efficks** [comment]
Hi @santiago-bassett,
I need to recompile ossec to change MAX_AGENTS. After, I need to generate the debian package.
I've try the generate_ossec.sh with --build but it fails with 

`2016-12-15 08:26:04: Error: Couldn't find changelog file for ossec-hids-2.8.2`

What it the process to start using generate_ossec.sh.
Do I need to install the app with InstallServer.sh before packaging? Where do I need to copy generate_ossec.sh?

Thank you for your help.

**Comment by crlorentzen** [comment]
@efficks I know it's a long time coming. But my company is working on utilizing OSSEC in their environment. and I am also trying to ensure I can put into our build pipeline OSSEC, specifically I am working off the release 2.9.0 version.

For right now, if you were still hoping to build yourself here is how to create the source debian structure needed
`mkdir -p /home/ubuntu/debian_files/version/{ossec-hids,ossec-hids-agent}/`
`tar -xvzf ossec-hids-version.tar.gz`
`cp -pr ossec-hids-version/contrib/debian-packages/ossec-hids/debian/ /home/ubuntu/debian_files/version/ossec-hids`
`cp -pr ossec-hids-version/contrib/debian-packages/ossec-hids-agent/debian/ /home/ubuntu/debian_files/version/ossec-hids-agent`

I have successfully ported most of the atomicorp RPM spec for use with our CentOS and RHEL hosts, however, I am just now learning debian packaging and am also trying to use the contributed tool here. Unfortunately the tool makes an assumption that everyone will have the same /home/ubuntu/debian_files folder preloaded with ossec-hids?debian and ossec-hids-agent/debian folder structures with up-to-date build instructions.

I am working on making it so that the structure makes use of the existing git structure which is also the built source tar.gz files. Also I will likely need to update some other build files if I want to put a pull request in.

@santiago-bassett Do you have plans to update the tools for 2.9.0? If I am able to I will submit a pull request when I have completed the work I am doing. My goals are

1. Update the generation script and build directives for 2.9.0
2. Update the generation script to work as a standalone download and use the debain build directives from the source tarball or git pull
2. A requirement at my company is that the install destination not be /var/ossec, so I will be extrapolating that and ensuring the make commands get the appropriate PREFIX entry.

I am not an expert, and my changes may or may not be exactly correct, as I am just learning debian packaging, pbuilder...etc.

**Comment by jwlynch** [comment]
> you can download debian/ubuntu already built packages from wazuh repo, you can find it here - http://documentation.wazuh.com/en/latest/ossec_installation_deb.html

nope, that page returns 404 not found

**Comment by atomicturtle** [comment]
We have the official ubuntu and debian packages available here:

https://updates.atomicorp.com/channels/atomic/ubuntu/

https://updates.atomicorp.com/channels/atomic/debian/
